apiVersion: v1
description: Elasticsearch light exporter for Prometheus
name: prometheus-elasticsearch-light-exporter
version: 1.0.0
kubeVersion: ">=1.10.0-0"
appVersion: 1.0.0
home: https://github.com/olivernadj/elasticsearch-light-exporter
sources:
  - https://github.com/olivernadj/elasticsearch-light-exporter/tree/main/helm-chart
keywords:
  - metrics
  - elasticsearch
  - monitoring
maintainers:
  - name: svenmueller
    email: sven.mueller@commercetools.com
  - name: caarlos0
    email: carlos@carlosbecker.com
  - name: desaintmartin
    email: cedric@desaintmartin.fr
  - name: olivernadj
    email: mr.oliver.nadj@gmail.com
