{{- if .Values.podSecurityPolicies.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{ template "elasticsearch-light-exporter.fullname" . }}
  labels:
    chart: {{ template "elasticsearch-light-exporter.chart" . }}
    app: {{ template "elasticsearch-light-exporter.name" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
rules:
- apiGroups: ['extensions']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - {{ template "elasticsearch-light-exporter.fullname" . }}
{{- end }}
